"""Package-wide configuration: schema constants and path resolution.

Kept dependency-free (stdlib only) so that importing the package never pays the
cost of loading pandas or anndata.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator

# 22-column schema shared by every CellMarker TSV file
# (see database/DATA_STRUCTURE.md).
COLUMNS: tuple[str, ...] = (
    "species",
    "tissue_class",
    "tissue_type",
    "uberon_id",
    "disease",
    "cell_name_class",
    "cell_name",
    "cellontology_id",
    "marker",
    "symbol",
    "gene_id",
    "gene_type",
    "gene_name",
    "uniprot_id",
    "technology_seq",
    "marker_source",
    "pmid",
    "title",
    "journal",
    "year",
    "series_id",
    "method_details",
)

# dataset key (canonical name) -> file name. The key equals the file basename
# minus the ".txt" extension.
DATASET_FILES: dict[str, str] = {
    "all_cell_marker": "all_cell_marker.txt",
    "human_cell_marker": "human_cell_marker.txt",
    "mouse_cell_marker": "mouse_cell_marker.txt",
    "single_cell_marker": "single_cell_marker.txt",
    "method_cell_marker": "method_cell_marker.txt",
}

# Verified value sets (database/DATA_STRUCTURE.md section 5.4).
MARKER_SOURCES: frozenset[str] = frozenset(
    {"Method", "Single-cell sequencing", "Experiment", "Review", "Company"}
)
METHOD_DETAILS: frozenset[str] = frozenset(
    {"COSG", "CelliD", "FindAllMarker", "Cepo", "SEMITONES", "Spapros"}
)

# Columns stored as float-like strings (e.g. "353156.0"); the trailing ".0"
# must be stripped before integer conversion (DATA_STRUCTURE.md section 7.1).
FLOAT_ID_COLUMNS: frozenset[str] = frozenset({"gene_id", "pmid", "year"})

# Columns with frequent empty values (DATA_STRUCTURE.md section 7.2).
COMMONLY_EMPTY_COLUMNS: frozenset[str] = frozenset(
    {"cellontology_id", "symbol", "gene_id", "uniprot_id", "technology_seq"}
)


@dataclass(frozen=True)
class ColumnSpec:
    """Per-column metadata."""

    float_like: bool = False  # stored as a float-like string (".0" suffix)
    commonly_empty: bool = False


COLUMN_SPECS: dict[str, ColumnSpec] = {
    "gene_id": ColumnSpec(float_like=True, commonly_empty=True),
    "pmid": ColumnSpec(float_like=True),
    "year": ColumnSpec(float_like=True),
    "cellontology_id": ColumnSpec(commonly_empty=True),
    "symbol": ColumnSpec(commonly_empty=True),
    "uniprot_id": ColumnSpec(commonly_empty=True),
    "technology_seq": ColumnSpec(commonly_empty=True),
}

# src layout: _config.py -> cellmarkerannot -> src -> project root.
PROJECT_ROOT: Path = Path(__file__).resolve().parents[2]

# Where the CellMarker TSV files live. Override at runtime with the
# CELLMARKERANNOT_DB_DIR environment variable (useful when this package is
# installed as a wheel elsewhere and has no local database/ directory).
DATABASE_DIR: Path = Path(
    os.environ.get("CELLMARKERANNOT_DB_DIR", PROJECT_ROOT / "database")
).resolve()


def get_database_path(dataset: str = "all_cell_marker") -> Path:
    """Resolve a dataset name to its TSV path.

    Raises ``ValueError`` for an unknown dataset name, and ``FileNotFoundError``
    if the file does not exist (use ``CELLMARKERANNOT_DB_DIR`` to point at a
    different database directory).
    """
    if dataset not in DATASET_FILES:
        raise ValueError(
            f"Unknown dataset {dataset!r}; choose from {sorted(DATASET_FILES)}"
        )
    path = DATABASE_DIR / DATASET_FILES[dataset]
    if not path.is_file():
        raise FileNotFoundError(
            f"Database file not found: {path} "
            "(set CELLMARKERANNOT_DB_DIR to override the database directory)"
        )
    return path


def iter_dataset_paths() -> Iterator[tuple[str, Path]]:
    """Yield ``(dataset_name, path)`` for every known dataset (no existence check)."""
    for name, file_name in DATASET_FILES.items():
        yield name, DATABASE_DIR / file_name


# Bundled Parquet store inside the package (shipped in the wheel). Generated by
# ``python -m cellmarkerannot.build_db`` from the source TSVs.
DATA_DIR: Path = Path(__file__).resolve().parent / "data"

# dataset key -> bundled parquet file name (same stem as the TSV).
PARQUET_FILES: dict[str, str] = {name: f"{name}.parquet" for name in DATASET_FILES}

# Schema/format version recorded in ``manifest.json``; bump on breaking changes.
SCHEMA_VERSION: str = "3.0.1"

# Manifest file name written by build_db into the data dir.
MANIFEST_FILE: str = "manifest.json"
